<a href="https://colab.research.google.com/github/Chasith-Randima/Large_Language_Model_Pytorch/blob/main/Basiz_Torch_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
randint = torch.randint(-100,100,(6,))
randint

tensor([ 75, -77,   3, -79, -71,  40])

In [3]:
tensor = torch.tensor([[0.1,1.2],[2.2,3.1],[4.9,5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [4]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [6]:
input = torch.empty(2,3)
input

tensor([[-2.0540e+05,  7.0065e-45, -2.6390e-33],
        [ 3.3188e-41,  8.9683e-44,  0.0000e+00]])

In [7]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [11]:
linspace = torch.linspace(3,10,steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [12]:
logspace = torch.logspace(start=-10,end=10,steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [15]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [16]:
a = torch.empty((2,3),dtype=torch.int64)
print(a)
empty_like = torch.empty_like(a)
empty_like

tensor([[101724310238000, 101724309697328,              64],
        [             80, 101710212509399,              96]])


tensor([[101724309713040, 101724309389072,              64],
        [             80, 101710211562955,              96]])