<a href="https://colab.research.google.com/github/Chasith-Randima/Large_Language_Model_Pytorch/blob/main/time_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np
import time
import torch.nn as nn

device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

cpu


In [ ]:
start_time = time.time()


# operation

zeros = torch.zeros(1,1)

# operation end

end_time = time.time()

elapsed_time = end_time -start_time

print(f"Elapsed Time {elapsed_time}")

Elapsed Time 0.03498077392578125


In [ ]:
torch_rand1 = torch.rand(100,100,100,100).to(device)
torch_rand2 = torch.rand(100,100,100,100).to(device)
np_rand1 = torch.rand(100,100,100,100)
np_rand2 = torch.rand(100,100,100,100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time}")

start_time = time.time()

rand = np.multiply(np_rand1,np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time}")

1.0793836116790771
0.3113996982574463


In [ ]:
probabilities = torch.tensor([0.1,0.9])

samples = torch.multinomial(probabilities,num_samples=10,replacement=True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [ ]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor,torch.tensor([5])),dim=0)
out

tensor([1, 2, 3, 4, 5])

In [ ]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [ ]:
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [ ]:
zeros = torch.zeros(2,3,4)

out = zeros.transpose(0,2)

out.shape

torch.Size([4, 3, 2])

In [ ]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

stacked_tensor = torch.stack([tensor1,tensor2,tensor3])

stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
import torch.nn as nn

sample = torch.tensor([10,10,10])

linear = nn.Linear(3,3,bias=False)

print(linear(sample))

RuntimeError: ignored

In [ ]:
import torch.nn.functional as F

tensor1 = torch.tensor([1.0,2.0,3.0])

softmax_output = F.softmax(tensor1,dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [ ]:
vocab_size = 1000
embedding_dim = 100
embedding = nn.Embedding(vocab_size,embedding_dim)

input_indices = torch.LongTensor([1,5,3,2])

embedded_output = embedding(input_indices)

print(embedded_output.shape)

torch.Size([4, 100])


In [ ]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])

print(a@b)
print(torch.matmul(a,b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [ ]:
# below randint generate random integer matrix in between 0 to 1 in shape of (3x2)

int_64 = torch.randint(1,(3,2)).float()


# below rand function generate random float matrix in shape of (2x3)
float_32 = torch.rand(2,3)

print(int_64.dtype,float_32.dtype)

# result = torch.matmul(int_64,float_32)

# print(result)

torch.float32 torch.float32
